import { readFile } from "fs/promises";
import path from "path";

/**
 * Late-fee payment records extracted from OGE reviewer annotations on filing
 * PDFs (e.g. "Filer paid late fee - HAJ 6/29/26" on the certification page).
 * Generated by the fee-annotation sweep; data/meta/fee-payments.json.
 */
export interface FeePayment {
  officialSlug: string | null;
  officialName: string;
  pdfFile: string;
  filingLabel: string | null;
  pdfUrl: string | null;
  annotationRaw: string;
  annotationCleaned: string;
  reviewerDate: string | null;
  /** "paid" — reviewer noted the fee was paid; "waived" — reviewer noted a
   * waiver. Both are enforcement outcomes worth displaying. */
  outcome: "paid" | "waived";
}

interface FeePaymentsFile {
  generated: string;
  method: string;
  payments: FeePayment[];
}

export async function getFeePayments(): Promise<FeePayment[]> {
  try {
    const raw = await readFile(
      path.join(process.cwd(), "data", "meta", "fee-payments.json"),
      "utf-8"
    );
    const parsed: FeePaymentsFile = JSON.parse(raw);
    return parsed.payments ?? [];
  } catch {
    // File absent until the first sweep runs — treat as no recorded payments.
    return [];
  }
}

export async function getFeePaymentsBySlug(
  slug: string
): Promise<FeePayment[]> {
  const payments = await getFeePayments();
  return payments.filter((p) => p.officialSlug === slug);
}
