/**
 * Per-row verification state: what checked each published row, and what
 * the check found.
 *
 * Until now the only record of verification was per filing, in
 * data/meta/crosscheck-log.json. A reader of a row could not tell whether
 * that row had been compared against anything. This module derives one
 * state per row from the filing-level log, the OCR lane's row alignment,
 * the second-model lane and human decisions, and a script writes the
 * result to data/meta/row-verification.json, which the loader reads for
 * pages and exports. The file is regenerated by
 * scripts/build-row-verification.ts; it is never edited by hand.
 *
 * Three gates, in Trevor's words (Sep 5): a program that never saw the
 * model's output (or, on unreadable scans, a second company's model), the
 * model read itself, and an audit in which a third company's model looks
 * at the page images beside the database rows the way a person would. A
 * row is "Checked" only when all three pass.
 *
 * Scores, highest first:
 *   3  checked               a program (text layer or OCR) or a second
 *                            model agreed on the row AND the audit confirmed
 *                            it against the page image
 *   3  human_verified        a person compared the row to the PDF and
 *                            recorded the decision (data/review/decisions.json)
 *   2  deterministic_agree   a program agreed; the audit has not run yet
 *   2  two_models_agree      a second company's model agreed; no program
 *                            could read the page; the audit has not run yet
 *   2  audit_only            the audit confirmed the row against the page,
 *                            but no program or second model has agreed yet
 *   1  single_read           one model read it and nothing has compared it
 *   0  disputed              any lane, or the audit, disagrees and no person
 *                            has decided; the row is marked under review
 *
 * A score is never raised by a program alone above what its lanes support,
 * and a human decision is the only thing that turns 0 into 3.
 */
import { createHash } from "crypto";
import { existsSync, readFileSync } from "fs";
import path from "path";
import type { Transaction } from "./types";
import type { CrosscheckEntry } from "./crosscheck-log";
import { normalizedDescription, sharesAssetWord } from "./reverify-diff";

export const ROW_VERIFICATION_PATH = path.join(process.cwd(), "data", "meta", "row-verification.json");
export const REVIEW_DECISIONS_PATH = path.join(process.cwd(), "data", "review", "decisions.json");

export type VerificationState =
  | "checked"
  | "human_verified"
  | "deterministic_agree"
  | "two_models_agree"
  | "audit_only"
  | "single_read"
  | "disputed";

export type VerificationLane = "text" | "ocr" | "model2" | "audit" | "human" | null;

export interface RowVerification {
  id: string;
  slug: string;
  score: 0 | 1 | 2 | 3;
  state: VerificationState;
  lane: VerificationLane;
  /** The source filing this row is stamped to, when known. */
  sourceUrl: string | null;
  /** One short reason, for the page and the export. */
  note: string;
}

export interface RowVerificationFile {
  version: 1;
  generatedAt: string;
  generatedBy: string;
  checkerVersion: string;
  summary: {
    rows: number;
    byState: Record<VerificationState, number>;
    byScore: Record<"0" | "1" | "2" | "3", number>;
  };
  rows: Record<string, RowVerification>;
}

/** A person's decision on one row, recorded by scripts/review.ts. */
export interface ReviewDecision {
  recordId: string;
  slug: string;
  decision: "confirmed" | "corrected" | "rejected";
  /** For "corrected": the row as it should read, applied by an approved patch. */
  correction?: Partial<Pick<Transaction, "type" | "date" | "amount" | "lateFilingFlag" | "ticker" | "description">>;
  evidence: string;
  decidedBy: string;
  decidedAt: string;
}

export const SCORE_FOR_STATE: Record<VerificationState, 0 | 1 | 2 | 3> = {
  checked: 3,
  human_verified: 3,
  deterministic_agree: 2,
  two_models_agree: 2,
  audit_only: 2,
  single_read: 1,
  disputed: 0,
};

/** Short marker text for a table cell. */
export const SHORT_LABEL: Record<VerificationState, string> = {
  checked: "Checked",
  human_verified: "Checked by a person",
  deterministic_agree: "Program agrees, audit pending",
  two_models_agree: "Two models agree, audit pending",
  audit_only: "Audit agrees, program pending",
  single_read: "Not yet checked",
  disputed: "Under review",
};

export const STATE_LABEL: Record<VerificationState, string> = {
  checked: "Checked: an independent program or a second model from another company read the same values, and a third model from a third company confirmed the row against the page image",
  human_verified: "Checked by a person against the filing",
  deterministic_agree: "An independent program read the same values from the filing; the page audit has not run yet",
  two_models_agree: "Two models read the same values; no program could read the page; the page audit has not run yet",
  audit_only: "The page audit confirmed this row; no independent program or second model has read it yet",
  single_read: "Not yet independently checked",
  disputed: "Under review: a check disagreed with this row",
};

/**
 * The seven fields a reader sees plus the occurrence index among identical
 * rows in the same official, so two lots of the same trade get different
 * IDs and a row's ID never depends on sort order.
 */
export function makeRecordId(tx: Transaction, occurrence: number): string {
  const parts = [
    tx.sourceUrl ?? "",
    tx.description.trim(),
    (tx.ticker ?? "").toUpperCase(),
    tx.type,
    tx.date,
    tx.amount ?? "unknown",
    tx.lateFilingFlag ? "1" : "0",
    String(occurrence),
  ];
  return createHash("sha256").update(parts.join("|")).digest("hex").slice(0, 24);
}

/** IDs for every row of one official, in the order given. */
export function recordIdsFor(transactions: Transaction[]): string[] {
  const seen = new Map<string, number>();
  return transactions.map((tx) => {
    const key = makeRecordId(tx, 0);
    const n = seen.get(key) ?? 0;
    seen.set(key, n + 1);
    return n === 0 ? key : makeRecordId(tx, n);
  });
}

/** The tuple the deterministic lanes compare. */
export function comparedTuple(tx: { type: string; date: string | null; amount: string | null; lateFilingFlag?: boolean }): string {
  const t = /^sale/i.test(tx.type) ? "Sale" : /^purchase/i.test(tx.type) ? "Purchase" : /^exchange/i.test(tx.type) ? "Exchange" : tx.type;
  return `${t}|${tx.date ?? "undated"}|${tx.amount ?? "unknown"}|${tx.lateFilingFlag ? "late" : "ontime"}`;
}

export interface DeriveInput {
  slug: string;
  transactions: Transaction[];
  /** Log entries for this official, by source URL. */
  entriesByUrl: Map<string, CrosscheckEntry>;
  /** For OCR-mismatch filings: the parse record rows in document order,
   * so a published row can be located at a printed position. */
  parseRecordByUrl: Map<string, Array<{ description: string; type: string; date: string | null; amount: string | null; lateFilingFlag?: boolean }>>;
  /** Second-model lane verdicts per filing: the parsed indexes it agreed
   * on and disagreed on. Absent until that lane runs. */
  model2ByUrl?: Map<string, { agreedIndexes: Set<number>; disputedIndexes: Set<number> }>;
  /** Audit lane verdicts per filing, by parsed index. Absent until it runs. */
  auditByUrl?: Map<string, { confirmed: Set<number>; disputed: Set<number>; notFound: Set<number> }>;
  decisionsById?: Map<string, ReviewDecision>;
}

/**
 * Locate each published row in the parse record for its filing by the
 * full tuple, consuming matches so lots pair one to one. Returns the
 * parsed index per published row, or -1.
 */
export function locateInParseRecord(
  rows: Transaction[],
  record: Array<{ description: string; type: string; date: string | null; amount: string | null; lateFilingFlag?: boolean }>
): number[] {
  type R = { description: string; type: string; date: string | null; amount: string | null; lateFilingFlag?: boolean };
  const exactKey = (r: R) => `${r.description.trim().toLowerCase()}|${comparedTuple(r)}`;
  // Wording-only differences (a ticker appended, a trailing symbol, a
  // spacing accident) do not make a different row. Second pass matches
  // the normalized name; third pass matches the trade tuple where the
  // names still share a distinctive word and the pairing is unambiguous.
  const nameKey = (r: R) => `${normalizedDescription(r.description)}|${comparedTuple(r)}`;
  const byExact = new Map<string, number[]>();
  const byName = new Map<string, number[]>();
  record.forEach((r, i) => {
    (byExact.get(exactKey(r)) ?? byExact.set(exactKey(r), []).get(exactKey(r))!).push(i);
    (byName.get(nameKey(r)) ?? byName.set(nameKey(r), []).get(nameKey(r))!).push(i);
  });
  const used = new Set<number>();
  const take = (bucket: number[] | undefined) => {
    while (bucket && bucket.length) {
      const i = bucket.shift()!;
      if (!used.has(i)) {
        used.add(i);
        return i;
      }
    }
    return -1;
  };
  const out = rows.map((tx) => take(byExact.get(exactKey(tx))));
  rows.forEach((tx, k) => {
    if (out[k] < 0) out[k] = take(byName.get(nameKey(tx)));
  });
  const leftover = record.map((_, i) => i).filter((i) => !used.has(i));
  rows.forEach((tx, k) => {
    if (out[k] >= 0) return;
    const t = comparedTuple(tx);
    const candidates = leftover.filter((i) => !used.has(i) && comparedTuple(record[i]) === t && sharesAssetWord(tx.description, record[i].description));
    if (candidates.length === 1) {
      used.add(candidates[0]);
      out[k] = candidates[0];
    }
  });
  return out;
}

/**
 * Printed row number for a parsed index, given the placeholder rows the
 * form numbers but the model omits. Inverse of the OCR lane's alignment.
 */
export function printedRowForIndex(index: number, placeholderRows: number[]): number {
  const placeholders = new Set(placeholderRows);
  let n = 0;
  let printed = 0;
  while (n <= index) {
    printed += 1;
    if (!placeholders.has(printed)) n += 1;
  }
  return printed;
}

/** Apply the audit gate to a provisional row state. */
export function applyAudit(
  v: RowVerification,
  audit: { confirmed: Set<number>; disputed: Set<number>; notFound: Set<number> } | undefined,
  parsedIndex: number
): RowVerification {
  if (v.state === "human_verified" || v.state === "disputed") return v;
  if (!audit || parsedIndex < 0) return v;
  if (audit.disputed.has(parsedIndex)) {
    return { ...v, score: 0, state: "disputed", lane: "audit", note: "The page audit read this row differently from the page image; a person decides" };
  }
  if (audit.notFound.has(parsedIndex)) {
    return { ...v, score: 0, state: "disputed", lane: "audit", note: "The page audit could not find this row on the filing's pages; a person decides" };
  }
  if (audit.confirmed.has(parsedIndex)) {
    if (v.state === "deterministic_agree" || v.state === "two_models_agree") {
      return { ...v, score: 3, state: "checked", note: `${v.note}; the page audit confirmed it` };
    }
    if (v.state === "single_read") {
      return { ...v, score: 2, state: "audit_only", lane: "audit", note: "The page audit confirmed this row against the page image; no program or second model has read it" };
    }
  }
  return v;
}

export function deriveRowVerification(input: DeriveInput): RowVerification[] {
  const ids = recordIdsFor(input.transactions);
  const out: RowVerification[] = [];
  // Group rows by filing so OCR alignment is computed once per filing.
  const located = new Map<string, number[]>();
  for (const [url, record] of input.parseRecordByUrl) {
    const rowsOfFiling = input.transactions.filter((t) => t.sourceUrl === url);
    located.set(url, locateInParseRecord(rowsOfFiling, record));
  }
  const perFilingCursor = new Map<string, number>();

  input.transactions.forEach((tx, i) => {
    const id = ids[i];
    const decision = input.decisionsById?.get(id);
    const base = { id, slug: input.slug, sourceUrl: tx.sourceUrl ?? null };
    const emit = (v: RowVerification, parsedIndex: number) => {
      out.push(applyAudit(v, tx.sourceUrl ? input.auditByUrl?.get(tx.sourceUrl) : undefined, parsedIndex));
    };
    if (decision && decision.decision !== "rejected") {
      out.push({ ...base, score: 3, state: "human_verified", lane: "human", note: `Decided by ${decision.decidedBy} on ${decision.decidedAt.slice(0, 10)}` });
      return;
    }
    if (!tx.sourceUrl) {
      out.push({ ...base, score: 1, state: "single_read", lane: null, note: "Not attributed to a specific filing; nothing has compared it" });
      return;
    }
    const entry = input.entriesByUrl.get(tx.sourceUrl);
    // Where this row sits in the candidate read of its filing, if the
    // candidate is on disk: -1 when not found, null when no candidate.
    const record = input.parseRecordByUrl.get(tx.sourceUrl);
    const positions = located.get(tx.sourceUrl);
    const cursor = perFilingCursor.get(tx.sourceUrl) ?? 0;
    perFilingCursor.set(tx.sourceUrl, cursor + 1);
    const parsedIndex: number | null = record && positions ? positions[cursor] : null;
    const m2 = input.model2ByUrl?.get(tx.sourceUrl);

    if (!entry) {
      emit({ ...base, score: 1, state: "single_read", lane: null, note: "No check has run on this filing" }, parsedIndex ?? -1);
      return;
    }
    // A filing-level agreement was between the lane and a candidate read.
    // It covers a published row only if that row is in the candidate.
    // (Review, Sep 6: a re-read can differ from what the site publishes,
    // and the log would then credit the site's row with the candidate's
    // check.) A row not found is a single read until a person or a patch
    // resolves it.
    if (parsedIndex === -1) {
      emit({ ...base, score: 1, state: "single_read", lane: null, note: "The checked read of this filing does not contain this row as published; a person reconciles" }, -1);
      return;
    }
    const idx = parsedIndex ?? -1;
    switch (entry.state) {
      case "checked_tuple_agreement":
        emit({ ...base, score: 2, state: "deterministic_agree", lane: "text", note: "Text layer of the filing agrees, row for row" }, idx);
        return;
      case "ocr_tuple_agreement":
        emit({ ...base, score: 2, state: "deterministic_agree", lane: "ocr", note: "OCR of the page image agrees, row for row" }, idx);
        return;
      case "checked_tuple_mismatch":
        // The text lane reports a mismatch for the filing, not the row.
        // A row a second model read the same way has two independent
        // reads agreeing; the page audit settles it. Otherwise the
        // filing's mismatch stands on the row.
        if (m2 && idx >= 0 && m2.agreedIndexes.has(idx)) {
          emit({ ...base, score: 2, state: "two_models_agree", lane: "model2", note: "A second model read the same values; the text layer disagrees with the model somewhere on this filing" }, idx);
        } else {
          emit({ ...base, score: 0, state: "disputed", lane: "text", note: "Text layer disagrees with the model on this filing; a person decides" }, idx);
        }
        return;
      case "ocr_tuple_mismatch": {
        // Per row: the OCR lane's alignment names the printed rows it
        // agreed on and disputed.
        const aligned = entry.ocr?.aligned;
        if (idx < 0 || !aligned) {
          emit({ ...base, score: 1, state: "single_read", lane: "ocr", note: "OCR could not locate this row; one model read it" }, idx);
          return;
        }
        const printed = printedRowForIndex(idx, aligned.placeholderRows ?? []);
        if (aligned.disputedPrintedRows?.includes(printed)) {
          // OCR is the weakest reader of a scan. When it disagrees but a
          // second model read the same values, two independent reads
          // agree and the page audit decides (applyAudit raises this to
          // checked, or drops it to disputed). The OCR disagreement stays
          // in the note. With no second read, OCR's dispute stands.
          if (m2?.agreedIndexes.has(idx)) {
            emit({ ...base, score: 2, state: "two_models_agree", lane: "model2", note: `A second model read the same values; OCR read printed row ${printed} differently` }, idx);
          } else {
            emit({ ...base, score: 0, state: "disputed", lane: "ocr", note: `OCR read printed row ${printed} differently; a person decides` }, idx);
          }
        } else if (aligned.repairedPrintedRows?.includes(printed)) {
          emit({ ...base, score: 1, state: "single_read", lane: "ocr", note: `OCR's row number for printed row ${printed} was repaired by sequence; not counted as a check` }, idx);
        } else if (aligned.agreedPrintedRows?.includes(printed)) {
          emit({ ...base, score: 2, state: "deterministic_agree", lane: "ocr", note: `OCR of printed row ${printed} agrees` }, idx);
        } else if (m2?.agreedIndexes.has(idx)) {
          emit({ ...base, score: 2, state: "two_models_agree", lane: "model2", note: "A second model read the same values; OCR could not read this row" }, idx);
        } else if (m2?.disputedIndexes.has(idx)) {
          emit({ ...base, score: 0, state: "disputed", lane: "model2", note: "A second model read this row differently; a person decides" }, idx);
        } else {
          emit({ ...base, score: 1, state: "single_read", lane: "ocr", note: `OCR could not read printed row ${printed}; one model read it` }, idx);
        }
        return;
      }
      default: {
        if (m2 && idx >= 0 && m2.agreedIndexes.has(idx)) {
          emit({ ...base, score: 2, state: "two_models_agree", lane: "model2", note: "A second model read the same values; no program could read the page" }, idx);
        } else if (m2 && idx >= 0 && m2.disputedIndexes.has(idx)) {
          emit({ ...base, score: 0, state: "disputed", lane: "model2", note: "A second model read this row differently; a person decides" }, idx);
        } else {
          const why =
            entry.state === "no_usable_text" ? "The filing is a scan no program has read" :
            entry.state === "unsupported_layout" ? "The filing's text could not be parsed by the checker" :
            entry.state === "unsupported_form" ? "The form type is not checked" :
            entry.state === "missing_local_document" ? "The filing PDF is not on disk" :
            "Nothing has compared this row";
          emit({ ...base, score: 1, state: "single_read", lane: null, note: why }, idx);
        }
      }
    }
  });
  return out;
}

let cache: RowVerificationFile | null = null;

export function readRowVerification(): RowVerificationFile | null {
  if (cache) return cache;
  if (!existsSync(ROW_VERIFICATION_PATH)) return null;
  cache = JSON.parse(readFileSync(ROW_VERIFICATION_PATH, "utf-8")) as RowVerificationFile;
  return cache;
}

export function resetRowVerificationCache(): void {
  cache = null;
}

export function readReviewDecisions(): Map<string, ReviewDecision> {
  if (!existsSync(REVIEW_DECISIONS_PATH)) return new Map();
  const list = JSON.parse(readFileSync(REVIEW_DECISIONS_PATH, "utf-8")) as { decisions: ReviewDecision[] };
  return new Map(list.decisions.map((d) => [d.recordId, d]));
}

/** Verification for every row of an official, in the official's row order. */
export function verificationForOfficial(slug: string, transactions: Transaction[]): (RowVerification | null)[] {
  const file = readRowVerification();
  if (!file) return transactions.map(() => null);
  return recordIdsFor(transactions).map((id) => file.rows[id] ?? null);
}
