/**
 * Per-row verification state: what checked each published row, and what
 * the check found.
 *
 * Until now the only record of verification was per filing, in
 * data/meta/crosscheck-log.json. A reader of a row could not tell whether
 * that row had been compared against anything. This module derives one
 * state per row from the filing-level log, the OCR lane's row alignment,
 * the second-model lane and human decisions, and a script writes the
 * result to data/meta/row-verification.json, which the loader reads for
 * pages and exports. The file is regenerated by
 * scripts/build-row-verification.ts; it is never edited by hand.
 *
 * Three gates, in Trevor's words (Sep 5): a program that never saw the
 * model's output (or, on unreadable scans, a second company's model), the
 * model read itself, and an audit in which a third company's model looks
 * at the page images beside the database rows the way a person would. A
 * row is "Checked" only when all three pass.
 *
 * Scores, highest first:
 *   3  checked               a program (text layer or OCR) or a second
 *                            model agreed on the row AND the audit confirmed
 *                            it against the page image
 *   3  human_verified        a person compared the row to the PDF and
 *                            recorded the decision (data/review/decisions.json)
 *   2  deterministic_agree   a program agreed; the audit has not run yet
 *   2  two_models_agree      a second company's model agreed; no program
 *                            could read the page; the audit has not run yet
 *   2  audit_only            the audit confirmed the row against the page,
 *                            but no program or second model has agreed yet
 *   1  single_read           one model read it and nothing has compared it
 *   0  disputed              any lane, or the audit, disagrees and no person
 *                            has decided; the row is marked under review
 *
 * A score is never raised by a program alone above what its lanes support,
 * and a human decision is the only thing that turns 0 into 3.
 */
import { createHash } from "crypto";
import { existsSync, readFileSync } from "fs";
import path from "path";
import type { Transaction } from "./types";
import type { CrosscheckEntry } from "./crosscheck-log";
import { editDistance, normalizedDescription, sharesAssetWord } from "./reverify-diff";

export const ROW_VERIFICATION_PATH = path.join(process.cwd(), "data", "meta", "row-verification.json");
export const REVIEW_DECISIONS_PATH = path.join(process.cwd(), "data", "review", "decisions.json");

export type VerificationState =
  | "checked"
  | "human_verified"
  | "deterministic_agree"
  | "two_models_agree"
  | "audit_only"
  | "single_read"
  | "implausible"
  | "disputed";

export type VerificationLane = "text" | "ocr" | "model2" | "audit" | "human" | null;

export interface RowVerification {
  id: string;
  slug: string;
  score: 0 | 1 | 2 | 3;
  state: VerificationState;
  lane: VerificationLane;
  /** The source filing this row is stamped to, when known. */
  sourceUrl: string | null;
  /** One short reason, for the page and the export. */
  note: string;
  /** What each gate said about this row, for the admin view. Absent on
   * rows built before Sep 6, 2026. */
  gates?: RowGates;
}

/** Per-gate verdicts for one row. "none" means the gate did not run or
 * could not see the row. */
export interface RowGates {
  /** The first read's own confidence for this row, 0 to 1, when recorded. */
  read1Confidence: number | null;
  text: "agree" | "disagree" | "none";
  ocr: "agree" | "disagree" | "repaired" | "unread" | "none";
  model2: "agree" | "disagree" | "unread" | "none";
  session: "agree" | "disagree" | "unread" | "none";
  audit: "confirm" | "dispute" | "notfound" | "none";
  human: "confirmed" | "corrected" | "rejected" | null;
  /** Reasons from the impossible-value check, empty when clean. */
  implausible: string[];
  /** Whether an independent reader read the same asset name. The text
   * lane compares names (a shared asset word); the second model and the
   * session read pair rows by name before comparing values, so either
   * verdict on the row means the name matched. OCR compares values only.
   * "none" means nobody independent has read this row's name; a ticker
   * is never attached to such a row (the Adobe-for-Apple case). */
  name: "agree" | "none";
}

export interface RowVerificationFile {
  version: 1;
  generatedAt: string;
  generatedBy: string;
  checkerVersion: string;
  summary: {
    rows: number;
    byState: Record<VerificationState, number>;
    byScore: Record<"0" | "1" | "2" | "3", number>;
  };
  rows: Record<string, RowVerification>;
}

/** A person's decision on one row, recorded by scripts/review.ts. */
export interface ReviewDecision {
  recordId: string;
  slug: string;
  decision: "confirmed" | "corrected" | "rejected";
  /** For "corrected": the row as it should read, applied by an approved patch. */
  correction?: Partial<Pick<Transaction, "type" | "date" | "amount" | "lateFilingFlag" | "ticker" | "description">>;
  evidence: string;
  decidedBy: string;
  decidedAt: string;
}

export const SCORE_FOR_STATE: Record<VerificationState, 0 | 1 | 2 | 3> = {
  checked: 3,
  human_verified: 3,
  deterministic_agree: 2,
  two_models_agree: 2,
  audit_only: 2,
  single_read: 1,
  implausible: 2,
  disputed: 0,
};

/** Short marker text for a table cell. */
export const SHORT_LABEL: Record<VerificationState, string> = {
  checked: "Checked",
  human_verified: "Checked by a person",
  deterministic_agree: "Program agrees, audit pending",
  two_models_agree: "Two models agree, audit pending",
  audit_only: "Audit agrees, program pending",
  single_read: "Not yet checked",
  implausible: "Needs a person: value cannot be right",
  disputed: "Under review",
};

export const STATE_LABEL: Record<VerificationState, string> = {
  checked: "Checked on type, date, amount and late flag: an independent program or a second model from another company read the same four values, and a third model from a third company, shown the row, confirmed it against the page image",
  human_verified: "Checked by a person against the filing",
  deterministic_agree: "An independent program read the same values from the filing; the page audit has not run yet",
  two_models_agree: "Two models read the same values; no program could read the page; the page audit has not run yet",
  audit_only: "The page audit confirmed this row; no independent program or second model has read it yet",
  single_read: "Not yet independently checked",
  implausible: "The readers agree, but a value cannot be right as read (a weekend trade date, a maturity before the trade, a date after the filing, or a misread word); a person decides",
  disputed: "Under review: a check disagreed with this row",
};

/**
 * The seven fields a reader sees plus the occurrence index among identical
 * rows in the same official, so two lots of the same trade get different
 * IDs and a row's ID never depends on sort order.
 */
export function makeRecordId(tx: Transaction, occurrence: number): string {
  const parts = [
    tx.sourceUrl ?? "",
    tx.description.trim(),
    (tx.ticker ?? "").toUpperCase(),
    tx.type,
    tx.date,
    tx.amount ?? "unknown",
    tx.lateFilingFlag ? "1" : "0",
    String(occurrence),
  ];
  return createHash("sha256").update(parts.join("|")).digest("hex").slice(0, 24);
}

/** IDs for every row of one official, in the order given. */
export function recordIdsFor(transactions: Transaction[]): string[] {
  const seen = new Map<string, number>();
  return transactions.map((tx) => {
    const key = makeRecordId(tx, 0);
    const n = seen.get(key) ?? 0;
    seen.set(key, n + 1);
    return n === 0 ? key : makeRecordId(tx, n);
  });
}

/** The tuple the deterministic lanes compare. */
export function comparedTuple(tx: { type: string; date: string | null; amount: string | null; lateFilingFlag?: boolean }): string {
  const t = /^sale/i.test(tx.type) ? "Sale" : /^purchase/i.test(tx.type) ? "Purchase" : /^exchange/i.test(tx.type) ? "Exchange" : tx.type;
  return `${t}|${tx.date ?? "undated"}|${tx.amount ?? "unknown"}|${tx.lateFilingFlag ? "late" : "ontime"}`;
}

export interface DeriveInput {
  slug: string;
  transactions: Transaction[];
  /** Log entries for this official, by source URL. */
  entriesByUrl: Map<string, CrosscheckEntry>;
  /** For OCR-mismatch filings: the parse record rows in document order,
   * so a published row can be located at a printed position. */
  parseRecordByUrl: Map<string, Array<{ description: string; type: string; date: string | null; amount: string | null; lateFilingFlag?: boolean }>>;
  /** Second-model lane verdicts per filing: the parsed indexes it agreed
   * on and disagreed on. Absent until that lane runs. */
  model2ByUrl?: Map<string, { agreedIndexes: Set<number>; disputedIndexes: Set<number> }>;
  /** The session page read alone (also merged into model2ByUrl by the
   * builder), so the admin view can show it as its own gate. */
  sessionByUrl?: Map<string, { agreedIndexes: Set<number>; disputedIndexes: Set<number>; unreadIndexes?: Set<number> }>;
  /** The second model alone, for the same reason. */
  model2OnlyByUrl?: Map<string, { agreedIndexes: Set<number>; disputedIndexes: Set<number>; unreadIndexes?: Set<number> }>;
  /** Audit lane verdicts per filing, by parsed index. Absent until it runs. */
  auditByUrl?: Map<string, { confirmed: Set<number>; disputed: Set<number>; notFound: Set<number> }>;
  decisionsById?: Map<string, ReviewDecision>;
  /** Posting date of each source filing, by URL, for the after-the-filing check. */
  filingDateByUrl?: Map<string, string>;
}

/**
 * Two descriptions are one asset with different wording: a ticker
 * appended, a spacing accident, one misread word ("Duo" for "Due"). Not
 * two bonds from the same issuer. sharesAssetWord accepts a shared first
 * word, which is right for a diff report and wrong for a locator: two
 * Harris County MUD bonds with the same trade values would pair, and one
 * would inherit the other's audit verdict (Codex, Sep 6). Here the word
 * sets must mostly overlap.
 */
export function sameAssetWording(a: string, b: string): boolean {
  const flat = (d: string) => normalizedDescription(d).replace(/ /g, "");
  const fa = flat(a);
  const fb = flat(b);
  if (fa === fb || (fa.length >= 6 && fb.length >= 6 && (fa.startsWith(fb) || fb.startsWith(fa)))) return true;
  // One or two characters off across the whole name is a misread letter
  // ("Progressive Corp On" for "Oh"), not another asset.
  if (fa.length >= 8 && fb.length >= 8 && editDistance(fa, fb) <= 2) return true;
  const words = (d: string) => new Set(normalizedDescription(d).split(" ").filter((w) => w.length >= 2));
  const wa = words(a);
  const wb = words(b);
  if (wa.size === 0 || wb.size === 0) return false;
  let shared = 0;
  for (const w of wa) if (wb.has(w)) shared += 1;
  const union = wa.size + wb.size - shared;
  return sharesAssetWord(a, b) && shared / union >= 0.6;
}

/**
 * Locate each published row in the parse record for its filing by the
 * full tuple, consuming matches so lots pair one to one. Returns the
 * parsed index per published row, or -1.
 */
export function locateInParseRecord(
  rows: Transaction[],
  record: Array<{ description: string; type: string; date: string | null; amount: string | null; lateFilingFlag?: boolean }>
): number[] {
  type R = { description: string; type: string; date: string | null; amount: string | null; lateFilingFlag?: boolean };
  const exactKey = (r: R) => `${r.description.trim().toLowerCase()}|${comparedTuple(r)}`;
  // Wording-only differences (a ticker appended, a trailing symbol, a
  // spacing accident) do not make a different row. Second pass matches
  // the normalized name; third pass matches the trade tuple where the
  // names still share a distinctive word and the pairing is unambiguous.
  const nameKey = (r: R) => `${normalizedDescription(r.description)}|${comparedTuple(r)}`;
  const byExact = new Map<string, number[]>();
  const byName = new Map<string, number[]>();
  record.forEach((r, i) => {
    (byExact.get(exactKey(r)) ?? byExact.set(exactKey(r), []).get(exactKey(r))!).push(i);
    (byName.get(nameKey(r)) ?? byName.set(nameKey(r), []).get(nameKey(r))!).push(i);
  });
  const used = new Set<number>();
  const take = (bucket: number[] | undefined) => {
    while (bucket && bucket.length) {
      const i = bucket.shift()!;
      if (!used.has(i)) {
        used.add(i);
        return i;
      }
    }
    return -1;
  };
  const out = rows.map((tx) => take(byExact.get(exactKey(tx))));
  rows.forEach((tx, k) => {
    if (out[k] < 0) out[k] = take(byName.get(nameKey(tx)));
  });
  const leftover = record.map((_, i) => i).filter((i) => !used.has(i));
  rows.forEach((tx, k) => {
    if (out[k] >= 0) return;
    const t = comparedTuple(tx);
    const candidates = leftover.filter((i) => !used.has(i) && comparedTuple(record[i]) === t && sameAssetWording(tx.description, record[i].description));
    if (candidates.length === 1) {
      used.add(candidates[0]);
      out[k] = candidates[0];
    }
  });
  return out;
}

/**
 * Printed row number for a parsed index, given the placeholder rows the
 * form numbers but the model omits. Inverse of the OCR lane's alignment.
 */
export function printedRowForIndex(index: number, placeholderRows: number[]): number {
  const placeholders = new Set(placeholderRows);
  let n = 0;
  let printed = 0;
  while (n <= index) {
    printed += 1;
    if (!placeholders.has(printed)) n += 1;
  }
  return printed;
}

/** Apply the audit gate to a provisional row state. */
export function applyAudit(
  v: RowVerification,
  audit: { confirmed: Set<number>; disputed: Set<number>; notFound: Set<number> } | undefined,
  parsedIndex: number
): RowVerification {
  if (v.state === "human_verified" || v.state === "disputed") return v;
  if (!audit || parsedIndex < 0) return v;
  if (audit.disputed.has(parsedIndex)) {
    return { ...v, score: 0, state: "disputed", lane: "audit", note: "The page audit read this row differently from the page image; a person decides" };
  }
  if (audit.notFound.has(parsedIndex)) {
    return { ...v, score: 0, state: "disputed", lane: "audit", note: "The page audit could not find this row on the filing's pages; a person decides" };
  }
  if (audit.confirmed.has(parsedIndex)) {
    if (v.state === "deterministic_agree" || v.state === "two_models_agree") {
      return { ...v, score: 3, state: "checked", note: `${v.note}; the page audit confirmed it` };
    }
    if (v.state === "single_read") {
      return { ...v, score: 2, state: "audit_only", lane: "audit", note: "The page audit confirmed this row against the page image; no program or second model has read it" };
    }
  }
  return v;
}

const MONTHS = "(?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Sept|Oct|Nov|Dec)[a-z]*";
const CRYPTO = /\b(?:bitcoin|ethereum|ether|crypto|solana|polkadot|cardano|litecoin|dogecoin|xrp|ripple|btc|eth|sol|ibit|fbtc|gbtc|ethe|etha|bitb|arkb|hodl|brrr)\b/i;

/**
 * Values no reader can be right about. When every lane agrees on a value
 * that cannot exist, agreement proves only that they all read the same
 * ink. Deterministic, never corrects anything, only names the reason so
 * a person looks. (Trevor, Sep 6.)
 *
 * - "Duo" before a month: the filing prints "Due"; the readers copied a
 *   misprint or misread it.
 * - A stock or bond trade dated on a Saturday or Sunday: markets are
 *   closed. Crypto trades every day, so those rows are exempt.
 * - A bond maturity year earlier than the trade year: nobody buys or
 *   sells a bond after it has matured.
 * - A trade dated after the filing was posted.
 */
export function implausibleValues(tx: Pick<Transaction, "description" | "date" | "ticker">, filingDate?: string | null): string[] {
  const out: string[] = [];
  const d = tx.description ?? "";
  if (new RegExp(`\\bDuo\\s+${MONTHS}\\b`, "i").test(d)) out.push('the name reads "Duo" before a month; the filing prints "Due"');
  const date = tx.date && /^\d{4}-\d{2}-\d{2}$/.test(tx.date) ? tx.date : null;
  if (date) {
    const year = Number(date.slice(0, 4));
    const dow = new Date(`${date}T12:00:00Z`).getUTCDay();
    if ((dow === 0 || dow === 6) && !CRYPTO.test(d) && !CRYPTO.test(tx.ticker ?? "")) {
      out.push(`the trade is dated a ${dow === 0 ? "Sunday" : "Saturday"} (${date}); markets are closed`);
    }
    const m = d.match(new RegExp(`\\bDue\\s+${MONTHS}\\s+\\d{1,2},?\\s*(\\d{4})\\b`, "i")) ?? d.match(/\bDUE\s+(?:ON\s+)?\d{1,2}\/\d{1,2}\/(\d{2,4})\b/i);
    if (m) {
      const raw = m[1];
      const maturity = raw.length === 2 ? 2000 + Number(raw) : Number(raw);
      if (maturity < year) out.push(`the bond matures in ${maturity}, before the ${year} trade`);
    }
    if (filingDate && /^\d{4}-\d{2}-\d{2}$/.test(filingDate) && date > filingDate) {
      out.push(`the trade is dated ${date}, after the filing was posted on ${filingDate}`);
    }
  }
  return out;
}

/** Cap a row below the top score when a value cannot be right. A person
 * who decided the row has already looked, so decided rows are left alone. */
export function applyImplausible(v: RowVerification, reasons: string[]): RowVerification {
  if (reasons.length === 0 || v.state === "human_verified") return v;
  const why = `Needs a person: ${reasons.join("; ")}`;
  if (v.score === 0) return { ...v, note: `${v.note}. ${why}` };
  return { ...v, score: 2, state: "implausible", note: `${why}. Before this check: ${v.note}` };
}

/** What each gate said about one row. Pure; used by the derivation. */
export function gatesForRow(
  input: DeriveInput,
  tx: Transaction,
  decision: ReviewDecision | undefined,
  parsedIndex: number,
  implausible: string[]
): RowGates {
  const url = tx.sourceUrl ?? "";
  const entry = url ? input.entriesByUrl.get(url) : undefined;
  const record = url ? input.parseRecordByUrl.get(url) : undefined;
  const conf = parsedIndex >= 0 && record ? (record[parsedIndex] as { confidence?: number } | undefined)?.confidence ?? null : null;
  const idx = parsedIndex;
  let text: RowGates["text"] = "none";
  let ocr: RowGates["ocr"] = "none";
  if (entry && idx >= 0) {
    if (entry.state === "checked_tuple_agreement") text = "agree";
    else if (entry.state === "checked_tuple_mismatch") text = "disagree";
    else if (entry.state === "ocr_tuple_agreement") ocr = "agree";
    else if (entry.state === "ocr_tuple_mismatch") {
      const aligned = entry.ocr?.aligned;
      if (aligned) {
        const printed = printedRowForIndex(idx, aligned.placeholderRows ?? []);
        if (aligned.disputedPrintedRows?.includes(printed)) ocr = "disagree";
        else if (aligned.repairedPrintedRows?.includes(printed)) ocr = "repaired";
        else if (aligned.agreedPrintedRows?.includes(printed)) ocr = "agree";
        else ocr = "unread";
      }
    }
  }
  const lane = (m?: { agreedIndexes: Set<number>; disputedIndexes: Set<number>; unreadIndexes?: Set<number> }): RowGates["model2"] =>
    !m || idx < 0 ? "none" : m.agreedIndexes.has(idx) ? "agree" : m.disputedIndexes.has(idx) ? "disagree" : m.unreadIndexes?.has(idx) ? "unread" : "none";
  const model2 = lane(url ? (input.model2OnlyByUrl ?? input.model2ByUrl)?.get(url) : undefined);
  const session = lane(url ? input.sessionByUrl?.get(url) : undefined);
  const a = url ? input.auditByUrl?.get(url) : undefined;
  const audit: RowGates["audit"] = !a || idx < 0 ? "none" : a.confirmed.has(idx) ? "confirm" : a.disputed.has(idx) ? "dispute" : a.notFound.has(idx) ? "notfound" : "none";
  const human: RowGates["human"] = decision ? decision.decision : null;
  const name: RowGates["name"] =
    text === "agree" || model2 === "agree" || model2 === "disagree" || session === "agree" || session === "disagree" || human === "confirmed" || human === "corrected"
      ? "agree"
      : "none";
  return { read1Confidence: conf, text, ocr, model2, session, audit, human, implausible, name };
}

export function deriveRowVerification(input: DeriveInput): RowVerification[] {
  const ids = recordIdsFor(input.transactions);
  const out: RowVerification[] = [];
  // Group rows by filing so OCR alignment is computed once per filing.
  const located = new Map<string, number[]>();
  for (const [url, record] of input.parseRecordByUrl) {
    const rowsOfFiling = input.transactions.filter((t) => t.sourceUrl === url);
    located.set(url, locateInParseRecord(rowsOfFiling, record));
  }
  const perFilingCursor = new Map<string, number>();

  input.transactions.forEach((tx, i) => {
    const id = ids[i];
    const decision = input.decisionsById?.get(id);
    const base = { id, slug: input.slug, sourceUrl: tx.sourceUrl ?? null };
    // Every row of a filing consumes one slot of its located positions,
    // decided rows included; otherwise a human decision on one row would
    // shift every row after it onto its neighbour's parse index. (Sep 6:
    // two decided rows made an agreed row below them read as disputed.)
    const cursor = tx.sourceUrl ? (perFilingCursor.get(tx.sourceUrl) ?? 0) : 0;
    if (tx.sourceUrl) perFilingCursor.set(tx.sourceUrl, cursor + 1);
    const earlyIndex = (): number => {
      const positions = tx.sourceUrl ? located.get(tx.sourceUrl) : undefined;
      return positions ? positions[cursor] : -1;
    };
    const reasons = implausibleValues(tx, tx.sourceUrl ? input.filingDateByUrl?.get(tx.sourceUrl) : null);
    const gatesAt = (parsedIndex: number): RowGates => gatesForRow(input, tx, decision, parsedIndex, reasons);
    const emit = (v: RowVerification, parsedIndex: number) => {
      out.push({ ...applyImplausible(applyAudit(v, tx.sourceUrl ? input.auditByUrl?.get(tx.sourceUrl) : undefined, parsedIndex), reasons), gates: gatesAt(parsedIndex) });
    };
    if (decision && decision.decision !== "rejected") {
      out.push({ ...base, score: 3, state: "human_verified", lane: "human", note: `Decided by ${decision.decidedBy} on ${decision.decidedAt.slice(0, 10)}`, gates: gatesAt(earlyIndex()) });
      return;
    }
    if (decision) {
      // A person rejected this row as published. Until an approved patch
      // changes it, no automatic agreement may lift it. (Codex, Sep 6: a
      // rejected row fell through and came back as "checked".)
      out.push({ ...base, score: 0, state: "disputed", lane: "human", note: `Rejected by ${decision.decidedBy} on ${decision.decidedAt.slice(0, 10)}; the row is wrong as published and waits for an approved patch`, gates: gatesAt(earlyIndex()) });
      return;
    }
    if (!tx.sourceUrl) {
      out.push({ ...applyImplausible({ ...base, score: 1, state: "single_read", lane: null, note: "Not attributed to a specific filing; nothing has compared it" }, reasons), gates: gatesAt(-1) });
      return;
    }
    const entry = input.entriesByUrl.get(tx.sourceUrl);
    // Where this row sits in the candidate read of its filing, if the
    // candidate is on disk: -1 when not found, null when no candidate.
    const record = input.parseRecordByUrl.get(tx.sourceUrl);
    const positions = located.get(tx.sourceUrl);
    const parsedIndex: number | null = record && positions ? positions[cursor] : null;
    const m2 = input.model2ByUrl?.get(tx.sourceUrl);

    if (!entry) {
      emit({ ...base, score: 1, state: "single_read", lane: null, note: "No check has run on this filing" }, parsedIndex ?? -1);
      return;
    }
    // A filing-level agreement was between the lane and a candidate read.
    // It covers a published row only if that row is in the candidate.
    // (Review, Sep 6: a re-read can differ from what the site publishes,
    // and the log would then credit the site's row with the candidate's
    // check.) A row not found is a single read until a person or a patch
    // resolves it.
    if (parsedIndex === -1) {
      emit({ ...base, score: 1, state: "single_read", lane: null, note: "The checked read of this filing does not contain this row as published; a person reconciles" }, -1);
      return;
    }
    const idx = parsedIndex ?? -1;
    switch (entry.state) {
      case "checked_tuple_agreement":
        emit({ ...base, score: 2, state: "deterministic_agree", lane: "text", note: "Text layer of the filing agrees, row for row" }, idx);
        return;
      case "ocr_tuple_agreement":
        emit({ ...base, score: 2, state: "deterministic_agree", lane: "ocr", note: "OCR of the page image agrees, row for row" }, idx);
        return;
      case "checked_tuple_mismatch":
        // The text lane reports a mismatch for the filing, not the row.
        // A row a second model read the same way has two independent
        // reads agreeing; the page audit settles it. Otherwise the
        // filing's mismatch stands on the row.
        if (m2 && idx >= 0 && m2.agreedIndexes.has(idx)) {
          emit({ ...base, score: 2, state: "two_models_agree", lane: "model2", note: "A second model read the same values; the text layer disagrees with the model somewhere on this filing" }, idx);
        } else {
          emit({ ...base, score: 0, state: "disputed", lane: "text", note: "Text layer disagrees with the model on this filing; a person decides" }, idx);
        }
        return;
      case "ocr_tuple_mismatch": {
        // Per row: the OCR lane's alignment names the printed rows it
        // agreed on and disputed.
        const aligned = entry.ocr?.aligned;
        if (idx < 0 || !aligned) {
          emit({ ...base, score: 1, state: "single_read", lane: "ocr", note: "OCR could not locate this row; one model read it" }, idx);
          return;
        }
        const printed = printedRowForIndex(idx, aligned.placeholderRows ?? []);
        if (aligned.disputedPrintedRows?.includes(printed)) {
          // OCR is the weakest reader of a scan. When it disagrees but a
          // second model read the same values, two independent reads
          // agree and the page audit decides (applyAudit raises this to
          // checked, or drops it to disputed). The OCR disagreement stays
          // in the note. With no second read, OCR's dispute stands.
          if (m2?.agreedIndexes.has(idx)) {
            emit({ ...base, score: 2, state: "two_models_agree", lane: "model2", note: `A second model read the same values; OCR read printed row ${printed} differently` }, idx);
          } else {
            emit({ ...base, score: 0, state: "disputed", lane: "ocr", note: `OCR read printed row ${printed} differently; a person decides` }, idx);
          }
        } else if (aligned.repairedPrintedRows?.includes(printed)) {
          // OCR cannot vouch for a row whose number it misread, but a
          // second model that read the same values still can. (Sep 6: 93
          // Trump rows sat at audit-only although the second model agreed
          // on every one, because this branch never asked it.)
          if (m2?.agreedIndexes.has(idx)) {
            emit({ ...base, score: 2, state: "two_models_agree", lane: "model2", note: `A second model read the same values; OCR's row number for printed row ${printed} was repaired by sequence` }, idx);
          } else if (m2?.disputedIndexes.has(idx)) {
            emit({ ...base, score: 0, state: "disputed", lane: "model2", note: `A second model read this row differently; OCR's row number for printed row ${printed} was repaired by sequence; a person decides` }, idx);
          } else {
            emit({ ...base, score: 1, state: "single_read", lane: "ocr", note: `OCR's row number for printed row ${printed} was repaired by sequence; not counted as a check` }, idx);
          }
        } else if (aligned.agreedPrintedRows?.includes(printed)) {
          emit({ ...base, score: 2, state: "deterministic_agree", lane: "ocr", note: `OCR of printed row ${printed} agrees` }, idx);
        } else if (m2?.agreedIndexes.has(idx)) {
          emit({ ...base, score: 2, state: "two_models_agree", lane: "model2", note: "A second model read the same values; OCR could not read this row" }, idx);
        } else if (m2?.disputedIndexes.has(idx)) {
          emit({ ...base, score: 0, state: "disputed", lane: "model2", note: "A second model read this row differently; a person decides" }, idx);
        } else {
          emit({ ...base, score: 1, state: "single_read", lane: "ocr", note: `OCR could not read printed row ${printed}; one model read it` }, idx);
        }
        return;
      }
      default: {
        if (m2 && idx >= 0 && m2.agreedIndexes.has(idx)) {
          emit({ ...base, score: 2, state: "two_models_agree", lane: "model2", note: "A second model read the same values; no program could read the page" }, idx);
        } else if (m2 && idx >= 0 && m2.disputedIndexes.has(idx)) {
          emit({ ...base, score: 0, state: "disputed", lane: "model2", note: "A second model read this row differently; a person decides" }, idx);
        } else {
          const why =
            entry.state === "no_usable_text" ? "The filing is a scan no program has read" :
            entry.state === "unsupported_layout" ? "The filing's text could not be parsed by the checker" :
            entry.state === "unsupported_form" ? "The form type is not checked" :
            entry.state === "missing_local_document" ? "The filing PDF is not on disk" :
            "Nothing has compared this row";
          emit({ ...base, score: 1, state: "single_read", lane: null, note: why }, idx);
        }
      }
    }
  });
  return out;
}

let cache: RowVerificationFile | null = null;

export function readRowVerification(): RowVerificationFile | null {
  if (cache) return cache;
  if (!existsSync(ROW_VERIFICATION_PATH)) return null;
  cache = JSON.parse(readFileSync(ROW_VERIFICATION_PATH, "utf-8")) as RowVerificationFile;
  return cache;
}

export function resetRowVerificationCache(): void {
  cache = null;
}

export function readReviewDecisions(): Map<string, ReviewDecision> {
  if (!existsSync(REVIEW_DECISIONS_PATH)) return new Map();
  const list = JSON.parse(readFileSync(REVIEW_DECISIONS_PATH, "utf-8")) as { decisions: ReviewDecision[] };
  return new Map(list.decisions.map((d) => [d.recordId, d]));
}

/** Verification for every row of an official, in the official's row order. */
export function verificationForOfficial(slug: string, transactions: Transaction[]): (RowVerification | null)[] {
  const file = readRowVerification();
  if (!file) return transactions.map(() => null);
  return recordIdsFor(transactions).map((id) => file.rows[id] ?? null);
}
